remove_ignored = true

[scalabel]
    [scalabel.imageSize]
    height = 720
    width = 1280

    [[scalabel.categories]]
    name = "direct"
    color = [219, 94, 86]

    [[scalabel.categories]]
    name = "alternative"
    color = [86, 211, 219]
