remove_ignored = true

[scalabel]
    [scalabel.imageSize]
    height = 720
    width = 1280

    [[scalabel.categories]]
    name = "road"
    color = [128, 64, 128]

    [[scalabel.categories]]
    name = "sidewalk"
    color = [244, 35, 232]

    [[scalabel.categories]]
    name = "building"
    color = [70, 70, 70]

    [[scalabel.categories]]
    name = "wall"
    color = [190, 153, 153]

    [[scalabel.categories]]
    name = "fence"
    color = [102, 102, 156]

    [[scalabel.categories]]
    name = "pole"
    color = [153, 153, 153]

    [[scalabel.categories]]
    name = "traffic light"
    color = [250, 170, 30]

    [[scalabel.categories]]
    name = "traffic sign"
    color = [220, 220, 0]

    [[scalabel.categories]]
    name = "vegetation"
    color = [107, 142, 35]

    [[scalabel.categories]]
    name = "terrain"
    color = [152, 251, 152]

    [[scalabel.categories]]
    name = "sky"
    color = [70, 130, 180]

    [[scalabel.categories]]
    name = "pedestrian"
    color = [220, 20, 60]

    [[scalabel.categories]]
    name = "rider"
    color = [255, 0, 0]

    [[scalabel.categories]]
    name = "car"
    color = [0, 0, 142]

    [[scalabel.categories]]
    name = "truck"
    color = [0, 0, 70]

    [[scalabel.categories]]
    name = "bus"
    color = [0, 60, 100]

    [[scalabel.categories]]
    name = "train"
    color = [0, 80, 100]

    [[scalabel.categories]]
    name = "motorcycle"
    color = [0, 0, 230]

    [[scalabel.categories]]
    name = "bicycle"
    color = [119, 11, 32]
